# Generated by Django 2.2.2 on 2019-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
