# Generated by Django 2.2.2 on 2019-06-21 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=1)),
                ('review_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.Games')),
            ],
        ),
    ]
