# Generated by Django 2.2.2 on 2019-06-21 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='review_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
