# Generated by Django 2.2.2 on 2019-06-21 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190621_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
