# Generated by Django 2.2.2 on 2019-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviews_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
