# Generated by Django 2.2.2 on 2019-06-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviews_is_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='ratings',
            new_name='difficulty',
        ),
        migrations.AddField(
            model_name='reviews',
            name='graphics',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='levels',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='price',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
            preserve_default=False,
        ),
    ]
