# Generated by Django 2.2.2 on 2019-06-21 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('site_link', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('posted_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('overview', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS4', 'PS4'), ('Xbox', 'Xbox')], max_length=50)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Anime', 'Anime'), ('Racing', 'Racing'), ('RPG', 'RPG'), ('Simulation', 'Simulation'), ('Sport', 'Sport'), ('Strategy', 'Strategy'), ('Survival', 'Survival'), ('VR', 'VR'), ('Horror', 'Horror'), ('Shooter', 'Shooter'), ('Puzzle', 'Puzzle'), ('OpenWorld', 'OpenWorld'), ('VisualNovel', 'VisualNovel')], max_length=50)),
                ('min_cpu', models.CharField(max_length=50)),
                ('min_ram', models.CharField(max_length=50)),
                ('min_os', models.CharField(max_length=50)),
                ('min_videocard', models.CharField(max_length=50)),
                ('min_storage', models.CharField(max_length=50)),
                ('rec_cpu', models.CharField(max_length=50)),
                ('rec_ram', models.CharField(max_length=50)),
                ('rec_os', models.CharField(max_length=50)),
                ('rec_videocard', models.CharField(max_length=50)),
                ('rec_storage', models.CharField(max_length=50)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('screenshot1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('screenshot2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('screenshot3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('screenshot4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('screenshot5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
