# Generated by Django 2.2.2 on 2019-06-23 02:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190621_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='platform',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PC', 'PC'), (' PS4', 'PS4'), (' Xbox', 'Xbox')], max_length=13),
        ),
    ]
