# Generated by Django 2.2.2 on 2019-06-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190623_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
